# -*- coding: utf-8 -*-
"""Golden AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmM-l8bLc9r1sSnh79bi9ivnN6hPcezi
"""

"""
Golden AI demo — core Python only (no FastAPI, no web UI).

Use in Google Colab or any Python environment. Typical installs::

    pip install numpy scikit-learn tensorflow
    # optional, to match the repo’s gold series without DuckDB:
    pip install yfinance pandas
    # optional, for quick plots in Colab:
    pip install matplotlib

Training target: min–max normalized series; window length 7; one-step-ahead prediction.
"""

from __future__ import annotations

import logging
import math
import os
import warnings
from typing import Any

import numpy as np

# -----------------------------------------------------------------------------
# Config (matches horizon/config.py defaults)
# -----------------------------------------------------------------------------

WINDOW = 7
EPOCHS = 80
REC_UNITS = 6
RIDGE_ALPHA = 1.0

KERAS_LEARNING_RATE = 0.002
KERAS_BATCH_SIZE = 50
KERAS_OPTIMIZER = "RMSprop"
KERAS_LOSS = "mse"

# -----------------------------------------------------------------------------
# TensorFlow / Keras (same quiet setup as horizon/tf_setup.py)
# -----------------------------------------------------------------------------

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)
    import tensorflow as tf

logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.get_logger().setLevel(logging.ERROR)
try:
    import absl.logging

    absl.logging.set_verbosity(absl.logging.ERROR)
except Exception:
    pass

keras = tf.keras

# -----------------------------------------------------------------------------
# Data: sliding windows → supervised (horizon/data_prep.py)
# -----------------------------------------------------------------------------


def window(series: np.ndarray, w: int) -> tuple[np.ndarray, np.ndarray]:
    """Build X of shape [n, w] and y of shape [n, 1] for one-step-ahead."""
    X = [series[i : i + w] for i in range(len(series) - w)]
    y = series[w:]
    return np.asarray(X, np.float32), np.asarray(y, np.float32).reshape(-1, 1)


def train_test_split_index(n_y: int) -> int:
    """First ~2/3 of supervised rows for train (horizon/lifespan.py)."""
    return int(np.ceil(2 * n_y / 3.0))

# -----------------------------------------------------------------------------
# Metrics (horizon/metrics.py)
# -----------------------------------------------------------------------------


def metrics_vector(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, Any]:
    y_true = np.asarray(y_true, dtype=np.float64).ravel()
    y_pred = np.asarray(y_pred, dtype=np.float64).ravel()
    err = y_true - y_pred
    mae = float(np.mean(np.abs(err)))
    rmse = float(np.sqrt(np.mean(err**2)))
    mse = float(np.mean(err**2))
    denom = np.maximum(np.abs(y_true), 1e-8)
    mape_pct = float(np.mean(np.abs(err) / denom) * 100.0)
    ss_res = float(np.sum(err**2))
    y_mean = float(np.mean(y_true))
    ss_tot = float(np.sum((y_true - y_mean) ** 2))
    r2 = float(1.0 - ss_res / ss_tot) if ss_tot > 1e-12 else None
    return {
        "n_samples": len(y_true),
        "mae": mae,
        "rmse": rmse,
        "mse": mse,
        "mape_pct": mape_pct,
        "r2": r2,
    }

# -----------------------------------------------------------------------------
# Denormalize to ₹/10g (horizon/denorm.py)
# -----------------------------------------------------------------------------


def normalized_to_price_10g_inr(
    normalized: np.ndarray,
    norm_lo: float,
    norm_hi: float,
    price_lo: float,
    price_hi: float,
) -> np.ndarray:
    a = np.asarray(normalized, dtype=np.float64).ravel()
    span_n = norm_hi - norm_lo
    span_p = price_hi - price_lo
    if span_n <= 0 or span_p <= 0:
        mid = 0.5 * (price_lo + price_hi) if math.isfinite(price_lo + price_hi) else price_lo
        return np.full_like(a, mid)
    return price_lo + (a - norm_lo) / span_n * span_p


# When Yahoo is unavailable, synthetic normalized series still maps to a plausible ₹/10g band for display.
ILLUSTRATIVE_PRICE_10G_INR_LO = 45_000.0
ILLUSTRATIVE_PRICE_10G_INR_HI = 95_000.0


def load_lab_series_prefer_yahoo(
    yahoo_start: str = "2015-01-01",
    synthetic_n: int = 400,
    synthetic_seed: int = 42,
) -> tuple[np.ndarray, float, float, float, float, str]:
    """
    Prefer Yahoo gold (real ₹/10g + matching normalized targets); otherwise synthetic + illustrative ₹ range.

    Returns ``(series, norm_lo, norm_hi, price_lo, price_hi, provenance_note)``.
    """
    try:
        series, n_lo, n_hi, p_lo, p_hi = fetch_gold_normalized_and_price_bounds(start=yahoo_start)
        return (
            series,
            float(n_lo),
            float(n_hi),
            float(p_lo),
            float(p_hi),
            "Yahoo GC=F * USDINR (INR per 10g 24k); denorm uses this sample min/max prices and normalized targets.",
        )
    except Exception as e:
        print(f"Could not load Yahoo gold ({e}). Using synthetic series with illustrative INR per 10g range.\n")
        s = synthetic_normalized_series(synthetic_n, seed=synthetic_seed)
        return (
            s,
            -1.0,
            1.0,
            ILLUSTRATIVE_PRICE_10G_INR_LO,
            ILLUSTRATIVE_PRICE_10G_INR_HI,
            "Synthetic normalized walk + illustrative INR per 10g band (not market data).",
        )


def print_predictions_inr(
    title: str,
    normalized_values: list[float] | np.ndarray,
    norm_lo: float,
    norm_hi: float,
    price_lo: float,
    price_hi: float,
    decimals: int = 2,
) -> None:
    """Print model outputs in normalized space and INR per 10g (24k)."""
    vals = [float(x) for x in np.asarray(normalized_values, dtype=np.float64).ravel()]
    inr = normalized_to_price_10g_inr(np.array(vals, dtype=np.float64), norm_lo, norm_hi, price_lo, price_hi)
    inr_list = [round(float(x), decimals) for x in np.asarray(inr).ravel()]
    print(title)
    print(f"  normalized: {vals}")
    print(f"  INR per 10g 24k: {inr_list}")


def print_actual_vs_predicted_sample_inr(
    y_true_norm: np.ndarray,
    y_pred_norm: np.ndarray,
    norm_lo: float,
    norm_hi: float,
    price_lo: float,
    price_hi: float,
    last_k: int = 5,
    decimals: int = 2,
    model_name: str = "model",
) -> None:
    """Last ``last_k`` test targets vs predictions in INR per 10g for quick sanity checks."""
    yt = np.asarray(y_true_norm, dtype=np.float64).ravel()
    yp = np.asarray(y_pred_norm, dtype=np.float64).ravel()
    if len(yt) == 0:
        return
    k = min(last_k, len(yt))
    sl = slice(-k, None)
    t_inr = normalized_to_price_10g_inr(yt[sl], norm_lo, norm_hi, price_lo, price_hi)
    p_inr = normalized_to_price_10g_inr(yp[sl], norm_lo, norm_hi, price_lo, price_hi)
    print(f"Last {k} test steps - actual vs {model_name} pred (INR per 10g 24k):")
    for i in range(k):
        print(
            f"  [{i - k}] actual {float(t_inr[i]):.{decimals}f} INR  pred {float(p_inr[i]):.{decimals}f} INR"
        )

# -----------------------------------------------------------------------------
# Ridge (horizon/ml_model.py)
# -----------------------------------------------------------------------------


def fit_ridge(X_train: np.ndarray, y_train: np.ndarray):
    from sklearn.linear_model import Ridge

    reg = Ridge(alpha=RIDGE_ALPHA)
    reg.fit(X_train.reshape(-1, WINDOW), y_train.ravel())
    return reg

# -----------------------------------------------------------------------------
# Keras stacks (horizon/keras_models.py)
# -----------------------------------------------------------------------------


def _compile(m):
    m.compile(
        optimizer=keras.optimizers.RMSprop(learning_rate=KERAS_LEARNING_RATE),
        loss=KERAS_LOSS,
    )
    return m


def build_rnn():
    return _compile(
        keras.Sequential(
            [
                keras.layers.Input(shape=(WINDOW, 1)),
                keras.layers.SimpleRNN(REC_UNITS),
                keras.layers.Dense(1),
            ]
        )
    )


def build_rnn_lstm():
    return _compile(
        keras.Sequential(
            [
                keras.layers.Input(shape=(WINDOW, 1)),
                keras.layers.SimpleRNN(REC_UNITS, return_sequences=True),
                keras.layers.LSTM(REC_UNITS),
                keras.layers.Dense(1),
            ]
        )
    )


def build_rnn_lstm_gru():
    return _compile(
        keras.Sequential(
            [
                keras.layers.Input(shape=(WINDOW, 1)),
                keras.layers.SimpleRNN(REC_UNITS, return_sequences=True),
                keras.layers.LSTM(REC_UNITS, return_sequences=True),
                keras.layers.GRU(REC_UNITS),
                keras.layers.Dense(1),
            ]
        )
    )


KERAS_BUILDERS = {
    "rnn": build_rnn,
    "rnn_lstm": build_rnn_lstm,
    "rnn_lstm_gru": build_rnn_lstm_gru,
}


def fit_keras_model(name: str, X_train_3d: np.ndarray, y_train: np.ndarray, epochs: int | None = None):
    epochs = EPOCHS if epochs is None else int(epochs)
    builder = KERAS_BUILDERS[name]
    m = builder()
    m.fit(
        X_train_3d,
        y_train,
        epochs=epochs,
        batch_size=KERAS_BATCH_SIZE,
        verbose=0,
    )
    return m

# -----------------------------------------------------------------------------
# One-step predictions & evaluation (horizon/evaluation.py, decoupled from app state)
# -----------------------------------------------------------------------------


def predict_plain_one_step(X: np.ndarray) -> np.ndarray:
    X = np.asarray(X, dtype=np.float32)
    return np.asarray(X[:, -1], dtype=np.float64)


def predict_ml_one_step(reg, X: np.ndarray) -> np.ndarray:
    X = np.asarray(X, dtype=np.float32)
    return np.asarray(reg.predict(X.reshape(-1, WINDOW)), dtype=np.float64).ravel()


def predict_keras_one_step(model, X: np.ndarray) -> np.ndarray:
    X = np.asarray(X, dtype=np.float32)
    return np.asarray(
        model.predict(X.reshape(-1, WINDOW, 1), verbose=0),
        dtype=np.float64,
    ).ravel()


def test_metrics_plain(X_test: np.ndarray, y_test: np.ndarray) -> dict[str, Any]:
    y_test = np.asarray(y_test, dtype=np.float64).ravel()
    return metrics_vector(y_test, predict_plain_one_step(X_test))


def test_metrics_ml(reg, X_test: np.ndarray, y_test: np.ndarray) -> dict[str, Any]:
    y_test = np.asarray(y_test, dtype=np.float64).ravel()
    return metrics_vector(y_test, predict_ml_one_step(reg, X_test))


def test_metrics_keras(model, X_test: np.ndarray, y_test: np.ndarray) -> dict[str, Any]:
    y_test = np.asarray(y_test, dtype=np.float64).ravel()
    return metrics_vector(y_test, predict_keras_one_step(model, X_test))

# -----------------------------------------------------------------------------
# Multi-step autoregressive roll (horizon/rolling.py)
# -----------------------------------------------------------------------------


def roll_plain(window_arr: np.ndarray, steps: int) -> list[float]:
    w = window_arr.astype(np.float32).copy()
    out: list[float] = []
    for _ in range(steps):
        nxt = float(w[-1])
        out.append(nxt)
        w = np.append(w[1:], nxt)
    return out


def roll_ml(reg, window_arr: np.ndarray, steps: int) -> list[float]:
    w = window_arr.astype(np.float32).copy()
    out: list[float] = []
    for _ in range(steps):
        x = w.reshape(1, WINDOW)
        nxt = float(reg.predict(x)[0])
        out.append(nxt)
        w = np.append(w[1:], nxt)
    return out


def roll_keras(model, window_arr: np.ndarray, steps: int) -> list[float]:
    w = window_arr.astype(np.float32).copy()
    out: list[float] = []
    for _ in range(steps):
        x = w.reshape(1, WINDOW, 1)
        nxt = float(model.predict(x, verbose=0)[0, 0])
        out.append(nxt)
        w = np.append(w[1:], nxt)
    return out

# -----------------------------------------------------------------------------
# Exploring the dataset (EDA before modeling)
# -----------------------------------------------------------------------------


def series_summary(series: np.ndarray, name: str = "series") -> dict[str, Any]:
    """Summary stats for the 1D target series (e.g. normalized_close)."""
    s = np.asarray(series, dtype=np.float64).ravel()
    fin = np.isfinite(s)
    return {
        "name": name,
        "length": int(s.size),
        "n_nan": int(np.isnan(s).sum()),
        "n_inf": int(np.isinf(s).sum()),
        "n_finite": int(fin.sum()),
        "min": float(np.nanmin(s)) if s.size else None,
        "max": float(np.nanmax(s)) if s.size else None,
        "mean": float(np.nanmean(s)) if fin.any() else None,
        "std": float(np.nanstd(s)) if fin.any() else None,
        "first_5": [float(x) for x in s[:5]] if s.size else [],
        "last_5": [float(x) for x in s[-5:]] if s.size else [],
    }


def first_difference_summary(series: np.ndarray) -> dict[str, Any]:
    """Day-to-day (step-to-step) changes — useful for random-walk intuition."""
    s = np.asarray(series, dtype=np.float64).ravel()
    if len(s) < 2:
        return {"n_steps": 0, "mean_delta": None, "std_delta": None}
    d = np.diff(s)
    return {
        "n_steps": int(d.size),
        "mean_delta": float(np.mean(d)),
        "std_delta": float(np.std(d)),
        "min_delta": float(np.min(d)),
        "max_delta": float(np.max(d)),
    }


def supervised_split_summary(
    X: np.ndarray,
    y: np.ndarray,
    split: int,
    window_size: int = WINDOW,
) -> dict[str, Any]:
    """How many sliding windows land in train vs test for one-step-ahead."""
    X = np.asarray(X)
    y = np.asarray(y)
    n = int(y.shape[0])
    split = int(split)
    n_train = min(split, n)
    n_test = max(0, n - split)
    return {
        "window_size": int(window_size),
        "n_supervised_rows": n,
        "n_features_per_row": int(X.shape[1]) if X.ndim == 2 else None,
        "split_index": split,
        "n_train_rows": n_train,
        "n_test_rows": n_test,
        "y_train_target_min": float(np.min(y[:split])) if n_train else None,
        "y_train_target_max": float(np.max(y[:split])) if n_train else None,
        "y_test_target_min": float(np.min(y[split:])) if n_test else None,
        "y_test_target_max": float(np.max(y[split:])) if n_test else None,
    }


def print_exploration_report(
    series: np.ndarray,
    X: np.ndarray,
    y: np.ndarray,
    split: int,
    series_name: str = "normalized_close",
) -> None:
    """Pretty-print summaries (works in Colab or terminal)."""
    import json

    blob = {
        "series": series_summary(series, name=series_name),
        "first_differences": first_difference_summary(series),
        "supervised_split": supervised_split_summary(X, y, split),
    }
    print(json.dumps(blob, indent=2, default=str))


def plot_series_optional(
    series: np.ndarray,
    title: str = "Series (normalized)",
    ylabel: str = "value",
    figsize: tuple[float, float] = (10, 3),
) -> Any:
    """
    Line plot of the 1D series. Returns the matplotlib figure, or ``None`` if matplotlib is missing.
    In Colab the figure usually displays automatically.
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return None

    s = np.asarray(series, dtype=np.float64).ravel()
    fig, ax = plt.subplots(figsize=figsize)
    ax.plot(np.arange(len(s)), s, linewidth=0.8)
    ax.set_title(title)
    ax.set_xlabel("time index (rows)")
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    return fig


def preview_forecast_duckdb(
    db_path: str,
    table: str = "forecast_observations",
    order_column: str = "observation_index",
    limit: int = 12,
    offset: int = 0,
) -> dict[str, Any]:
    """
    Peek at rows like the web ``/data`` page: column names, total count, and a page of records.

    Requires: pip install duckdb pandas
    """
    import re

    ident = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

    def sql_ident(name: str) -> str:
        if not ident.fullmatch(name):
            raise ValueError(f"Invalid SQL identifier: {name!r}")
        return name

    import duckdb

    table = sql_ident(table)
    order_column = sql_ident(order_column)
    limit = int(limit)
    offset = int(offset)
    if limit < 1 or offset < 0:
        raise ValueError("limit must be >= 1 and offset >= 0")

    con = duckdb.connect(db_path, read_only=True)
    try:
        total = int(con.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])
        cur = con.execute(
            f"SELECT * FROM {table} ORDER BY {order_column} LIMIT ? OFFSET ?",
            [limit, offset],
        )
        col_names = [d[0] for d in cur.description or []]
        raw_rows = cur.fetchall()
        rows = [dict(zip(col_names, row)) for row in raw_rows]
        return {
            "db_path": db_path,
            "table": table,
            "total_rows": total,
            "limit": limit,
            "offset": offset,
            "columns": col_names,
            "rows": rows,
        }
    finally:
        con.close()


def fetch_yahoo_gold_lab_frame(start: str = "2010-01-01"):
    """
    Yahoo gold as a **pandas** table for inspection: dates, ``price_10g_inr``,
    and ``normalized_close`` (full-sample min–max to [-1, 1], same as the demo DB).

    Requires: pip install yfinance pandas
    """
    import contextlib
    import io

    import pandas as pd
    import yfinance as yf

    _GRAMS_PER_TROY_OZ = 31.1034768

    buf_out = io.StringIO()
    buf_err = io.StringIO()
    with contextlib.redirect_stdout(buf_out), contextlib.redirect_stderr(buf_err):
        usdoz = yf.Ticker("GC=F").history(start=start, auto_adjust=True)
        inr = yf.Ticker("USDINR=X").history(start=start, auto_adjust=True)
    if usdoz.empty or inr.empty:
        raise RuntimeError("Yahoo returned empty history - check start date or network.")

    usdoz = usdoz["Close"].astype(np.float64)
    inr = inr["Close"].astype(np.float64)
    joined = pd.concat([usdoz, inr], axis=1, join="inner")
    joined.columns = ["gc_usd_oz", "usd_inr"]
    joined = joined.dropna()
    if len(joined) == 0:
        raise RuntimeError(
            "No overlapping GC=F and USDINR=X rows after join - try a later start= date or check network."
        )
    inr_per_10g = (joined["gc_usd_oz"] * joined["usd_inr"]) / _GRAMS_PER_TROY_OZ * 10.0
    df = pd.DataFrame({"price_10g_inr": inr_per_10g})
    lo_p, hi_p = float(df["price_10g_inr"].min()), float(df["price_10g_inr"].max())
    if hi_p <= lo_p:
        df["normalized_close"] = 0.0
    else:
        df["normalized_close"] = 2.0 * (df["price_10g_inr"] - lo_p) / (hi_p - lo_p) - 1.0
    return df


# -----------------------------------------------------------------------------
# Optional data sources for Colab
# -----------------------------------------------------------------------------


def synthetic_normalized_series(n: int = 500, seed: int = 42) -> np.ndarray:
    """Random walk in [-1, 1] space — no extra packages."""
    rng = np.random.default_rng(seed)
    steps = rng.normal(0, 0.05, size=n)
    s = np.cumsum(steps).astype(np.float64)
    lo, hi = float(s.min()), float(s.max())
    if hi <= lo:
        return np.zeros(n, dtype=np.float32)
    norm = 2.0 * (s - lo) / (hi - lo) - 1.0
    return norm.astype(np.float32)


def load_series_from_duckdb_file(
    db_path: str,
    table: str = "forecast_observations",
    order_column: str = "observation_index",
    value_column: str = "normalized_close",
    max_rows: int = 0,
) -> np.ndarray:
    """
    Same idea as horizon/db.py — use if you upload ``normalized_forecast_series.duckdb``.
    Requires: pip install duckdb
    """
    import re

    ident = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

    def sql_ident(name: str) -> str:
        if not ident.fullmatch(name):
            raise ValueError(f"Invalid SQL identifier: {name!r}")
        return name

    import duckdb

    table = sql_ident(table)
    order_column = sql_ident(order_column)
    value_column = sql_ident(value_column)
    con = duckdb.connect(db_path, read_only=True)
    try:
        if max_rows > 0:
            q = f"""
            SELECT {value_column} AS v FROM {table}
            ORDER BY {order_column} DESC
            LIMIT ?
            """
            df = con.execute(q, [max_rows]).df()
            s = df["v"].to_numpy(dtype=np.float32)[::-1].copy()
        else:
            q = f"SELECT {value_column} AS v FROM {table} ORDER BY {order_column}"
            s = con.execute(q).df()["v"].to_numpy(dtype=np.float32)
        return s
    finally:
        con.close()


def fetch_gold_normalized_and_price_bounds(
    start: str = "2010-01-01",
) -> tuple[np.ndarray, float, float, float, float]:
    """
    Spot-implied gold (``fetch_yahoo_gold_lab_frame``): normalized series + bounds for ₹/10g.
    Aligns with scripts/import_gold_yfinance_to_duckdb.py.

    Requires: pip install yfinance pandas
    """
    df = fetch_yahoo_gold_lab_frame(start=start)
    norm = df["normalized_close"].to_numpy(dtype=np.float32)
    if norm.size == 0:
        raise RuntimeError("Gold series has no rows.")
    lo_p, hi_p = float(df["price_10g_inr"].min()), float(df["price_10g_inr"].max())
    return norm, float(norm.min()), float(norm.max()), lo_p, hi_p


# -----------------------------------------------------------------------------
# Example driver (students can copy cells instead of running this block)
# -----------------------------------------------------------------------------


def _demo() -> None:
    series, n_lo, n_hi, p_lo, p_hi, provenance = load_lab_series_prefer_yahoo()
    print("Data:", provenance)
    print(f"  norm scale [{n_lo:g}, {n_hi:g}]  <->  INR per 10g [{p_lo:,.2f}, {p_hi:,.2f}]")

    X, y = window(series, WINDOW)
    split = train_test_split_index(len(y))
    print_exploration_report(series, X, y, split)
    X_train, y_train = X[:split], y[:split]
    X_test, y_test = X[split:], y[split:]

    print("Plain baseline (test):", test_metrics_plain(X_test, y_test))

    reg = fit_ridge(X_train, y_train)
    print("Ridge (test):", test_metrics_ml(reg, X_test, y_test))

    X_train_3d = X_train.reshape(-1, WINDOW, 1)
    model = fit_keras_model("rnn", X_train_3d, y_train, epochs=min(EPOCHS, 30))
    print("SimpleRNN (test):", test_metrics_keras(model, X_test, y_test))

    last_window = X_test[-1] if len(X_test) else X_train[-1]
    roll_norm = roll_ml(reg, last_window, 5)
    print_predictions_inr(
        "5-step ahead autoregressive roll (Ridge)",
        roll_norm,
        n_lo,
        n_hi,
        p_lo,
        p_hi,
    )
    ridge_pred = predict_ml_one_step(reg, X_test)
    print_actual_vs_predicted_sample_inr(
        y_test,
        ridge_pred,
        n_lo,
        n_hi,
        p_lo,
        p_hi,
        model_name="Ridge",
    )

    rnn_pred = predict_keras_one_step(model, X_test)
    print_actual_vs_predicted_sample_inr(
        y_test,
        rnn_pred,
        n_lo,
        n_hi,
        p_lo,
        p_hi,
        model_name="SimpleRNN",
    )


if __name__ == "__main__":
    _demo()